apiVersion: v1
kind: Template
parameters:
- name: ODS_BITBUCKET_PROJECT
  description: Bitbucket project name.
  value: opendevstack
- name: REPO_BASE
  description: repository base url. In case bitbucket is used, needs to include /scm - so it's the path in front on opendevstack/..
  required: true
- name: ODS_GIT_REF
  required: true
- name: PROJECT_ID
  description: Project identifier
  required: true
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PROJECT_ID}-cd
      component: elasticsearch
      template: bc-docker
    name: elasticsearch
  spec:
    failedBuildsHistoryLimit: 5
    successfulBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: elasticsearch:7.0.0
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: airflow-cluster/base-images/elasticsearch
      git:
        ref: ${ODS_GIT_REF}
        uri: ${REPO_BASE}/${ODS_BITBUCKET_PROJECT}/ods-quickstarters.git
      sourceSecret:
        name: cd-user-with-password
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    triggers: []
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PROJECT_ID}-cd
      component: airflow
      template: bc-docker
    name: airflow
  spec:
    failedBuildsHistoryLimit: 5
    successfulBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: airflow:1.10.3
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: airflow-cluster/base-images/airflow
      git:
        ref: ${ODS_GIT_REF}
        uri: ${REPO_BASE}/${ODS_BITBUCKET_PROJECT}/ods-quickstarters.git
      sourceSecret:
        name: cd-user-with-password
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    triggers: []
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: elasticsearch
    labels:
      app: ${PROJECT_ID}-cd
      component: elasticsearch
      template: bc-docker
  spec:
    dockerImageRepository: elasticsearch
    lookupPolicy:
      local: false
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${PROJECT_ID}-cd
      component: airflow
      template: bc-docker
    name: airflow
  spec:
    dockerImageRepository: airflow
    lookupPolicy:
      local: false
