apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.airflow-webserver: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"airflow-webserver"}}'
  labels:
    cluster: airflow
  name: airflow
