def odsNamespace = env.ODS_NAMESPACE ?: 'ods'
def odsGitRef = env.ODS_GIT_REF ?: 'master'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'

library("ods-jenkins-shared-library@${odsGitRef}")

odsQuickstarterPipeline(
    imageStreamTag: "${odsNamespace}/jenkins-agent-graalvm:${odsImageTag}",
) { context ->

  stage('Build Quarkus project') {

    // quarkus-maven-plugin creates the project folder and fails if this is already existing
    sh "rm -r ${context.targetDir}"

    // create quarkus project
    def quarkusVersion = "1.9.2.Final"
    sh "mvn io.quarkus:quarkus-maven-plugin:${quarkusVersion}:create \
        -DprojectGroupId=${context.projectId} \
        -DprojectArtifactId=${context.componentId} \
        -DclassName='${context.projectId}.getting.started.GreetingResource' \
        -Dpath='/hello' \
        -DbuildTool=gradle"

    // add nexus credential settings to build.gradle
    sh "cat ${context.sourceDir}/templates/gradle-buildscript.template ${context.targetDir}/build.gradle >out && mv out ${context.targetDir}/build.gradle"

    // insert required plugins to build.gradle
    sh "sed -i -e '/plugins {/{r ${context.sourceDir}/templates/gradle-plugins.template' -e 'd' -e '}' ${context.targetDir}/build.gradle"

    // insert nexus repos to build.gradle
    sh "sed -i -e '/mavenCentral()/{r ${context.sourceDir}/templates/gradle-repositories.template' -e 'd' -e '}' ${context.targetDir}/build.gradle"

    // insert test settings to build.gradle
    sh "sed -i -e '/test {/{r ${context.sourceDir}/templates/gradle-plugin-test.template' -e 'd' -e '}' ${context.targetDir}/build.gradle"

    // append asciidoctor settings to build.gradle
    sh "cat ${context.sourceDir}/templates/gradle-plugin-asciidoctor.template >> ${context.targetDir}/build.gradle"

    // append jacoco settings to build.gradle
    sh "cat ${context.sourceDir}/templates/gradle-plugin-jacoco.template >> ${context.targetDir}/build.gradle"

    // append custom properties to gradle.properties
    sh "cat ${context.sourceDir}/templates/gradle-properties.template >> ${context.targetDir}/gradle.properties"

    // move docker dir to expected location
    sh "mv ${context.targetDir}/src/main/docker ${context.targetDir}"

    // for docker versions that can't handle '--chown' we replace a line in Dockerfile.native that uses it
    sh "sed -i -e '/COPY --chown=1001:root build\\/\\*-runner \\/work\\/application/{r ${context.sourceDir}/templates/dockerfile-native-chown.template' -e 'd' -e '}' ${context.targetDir}/docker/Dockerfile.native"
  }

  odsQuickstarterStageCopyFiles(context)

  odsQuickstarterStageCreateOpenShiftResources(
      context,
      [directory: 'common/ocp-config/component-environment']
  )

  odsQuickstarterStageRenderJenkinsfile(context)

  odsQuickstarterStageRenderSonarProperties(context)
}
